# config.toml

iters = 5000
env_size = 100.0
turnback = 0.1
layout = 16

[[flocks]]
flock.name = "Alpha"
flock.kind.kind = "Hawk"
flock.kind.size = 3.0
flock.kind.color = [255, 0, 0]
flock.kind.preys = ["Pigeon", "Hawk"]
flock.kind.predators = ["Hawk"]
flock.kind.speed.min = 1.0
flock.kind.speed.max = 2.0
flock.kind.angular_speed.min = 0.0
flock.kind.angular_speed.max = 0.025
flock.kind.acceleration.min = -0.1
flock.kind.acceleration.max = 0.1
flock.kind.momentum = 0.75
flock.kind.vision.min = 0.0
flock.kind.vision.max = 60.0
flock.kind.protected.min = 0.0
flock.kind.protected.max = 30.0
flock.kind.sep_weight = 0.05
flock.kind.align_weight = 0.05
flock.kind.coh_weight = 0.05
boids = 3
state.min = 0.75
state.max = 1.0
biases = []

[[flocks]]
flock.name = "Beta"
flock.kind.kind = "Pigeon"
flock.kind.size = 2.0
flock.kind.color = [0, 255, 0]
flock.kind.preys = ["Bug"]
flock.kind.predators = ["Hawk"]
flock.kind.speed.min = 1.0
flock.kind.speed.max = 2.5
flock.kind.angular_speed.min = 0.0
flock.kind.angular_speed.max = 0.05
flock.kind.acceleration.min = -0.2
flock.kind.acceleration.max = 0.2
flock.kind.momentum = 0.5
flock.kind.vision.min = 0.0
flock.kind.vision.max = 40.0
flock.kind.protected.min = 0.0
flock.kind.protected.max = 20.0
flock.kind.sep_weight = 0.05
flock.kind.align_weight = 0.05
flock.kind.coh_weight = 0.05
boids = 5
state.min = 0.5
state.max = 1.0
biases = []

[[flocks]]
flock.name = "Gamma"
flock.kind.kind = "Bug"
flock.kind.size = 1.0
flock.kind.color = [0, 0, 255]
flock.kind.preys = []
flock.kind.predators = ["Pigeon"]
flock.kind.speed.min = 1.0
flock.kind.speed.max = 3.0
flock.kind.angular_speed.min = 0.0
flock.kind.angular_speed.max = 0.075
flock.kind.acceleration.min = -0.2
flock.kind.acceleration.max = 0.2
flock.kind.momentum = 0.25
flock.kind.vision.min = 0.0
flock.kind.vision.max = 20.0
flock.kind.protected.min = 0.0
flock.kind.protected.max = 10.0
flock.kind.sep_weight = 0.05
flock.kind.align_weight = 0.05
flock.kind.coh_weight = 0.05
boids = 20
state.min = 0.25
state.max = 1.0

[[flocks.biases]]
position = [0.0, 0.0, 0.0]
weight_range = { min = 0.00025, max = 0.0005 }
prob = 0.25

[[flocks.biases]]
position = [0.0, 0.0, 0.0]
weight_range = { min = -0.0005, max = -0.00025 }
prob = 0.25